FROM fluidity/baseimages:bionic

USER root
RUN apt-get -y update
RUN apt-get -y dist-upgrade

ADD /home/runner/work/fluidity/fluidity /home/fluidity
RUN chown -r fluidity /home/fluidity/fluidity

USER fluidity

WORKDIR /home/fluidity/fluidity

ENV PETSC_DIR /usr/lib/petscdir/3.8

RUN ./configure --enable-2d-adaptivity
RUN make
RUN make fltools
