FROM fluidity/baseimages:bionic

USER root
RUN apt-get -y update && apt-get -y dist-upgrade && rm -f /var/cache/apt/archives/*deb

COPY . /home/fluidity
RUN chown -R fluidity /home/fluidity

USER fluidity

ENV PETSC_DIR /usr/lib/petscdir/3.8

RUN ./configure --enable-2d-adaptivity
RUN make
RUN make fltools
